name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Run Vue tests"
        run: yarn test:vue
      - name: "Run firebase tests"
        run: firebase emulators:exec "FIRESTORE_EMULATOR_HOST=localhost:8090 yarn run mocha test/firebase/**/*.js --exit"
