name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

  test:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: "Run Vue tests"
        run: yarn test:vue

  lint:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: "Lint"
        run: yarn lint

  release:
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    steps:
      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
